#!/bin/sh

# PIN code at 0x1FE00 in breed bootloader
PINCODE=$(dd if=/dev/mtd0 bs=1 count=8 skip=130560)
# WiFi SSID in format of "OpenWrt-<MAC>"
MACADDR=$(ip link | grep wlan0: -A 1 | tail -n 1 | awk '{gsub(/:/,""); print toupper($2)}')
WIFISSID=OpenWrt-$MACADDR

uci set luci.apply.rollback=300
[ "$PINCODE" != 00000000 ] && uci set wireless.radio0.disabled=0
uci set wireless.default_radio0.ssid=$WIFISSID
uci set wireless.radio0.country='CN'
uci set wireless.radio0.channel='auto'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
echo CST-8 > /etc/TZ
uci commit
wifi

sleep 3
rm /etc/rc.local.d/00firstboot
